# -*- coding: utf-8 -*-
"""havadurumu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMQu1LeeyQdvWttuzKxiCgl_VGkKpo-u
"""

"""Sehir Sınıfı
Her bir şehri ve sıcaklık bilgisini temsil eder.
__init__(self, ad, sicaklik): Şehrin adı ve sıcaklık bilgisi ile bir Sehir nesnesi oluşturur.
__str__(self): Şehir adını ve sıcaklık bilgisini okunabilir bir formatta döndürür.

HavaDurumu Sınıfı
Birden fazla şehir ve onların sıcaklık bilgilerini yönetmek için kullanılır.
__init__(self): Boş bir şehir listesi oluşturur.
sehir_ekle(self, ad, sicaklik): Şehir ve sıcaklık bilgisini alarak listeye ekler.
sicaklik_sorgula(self, ad): Belirtilen şehrin sıcaklık bilgisini döndürür. Eğer şehir bulunamazsa None döner.
tavsiye_ver(self, sicaklik): Sıcaklığa göre kıyafet önerisi döndürür.
listele(self): Kayıtlı tüm şehirlerin sıcaklık bilgilerini listeler. """


class Sehir:
    def __init__(self, ad, sicaklik):
        self.ad = ad
        self.sicaklik = sicaklik

    def __str__(self):
        return f"{self.ad} - {self.sicaklik}°C"


class HavaDurumu:
    def __init__(self):
        self.sehirler = []

    def sehir_ekle(self, ad, sicaklik):
        self.sehirler.append(Sehir(ad, sicaklik))

    def sicaklik_sorgula(self, ad):
        for sehir in self.sehirler:
            if sehir.ad.lower() == ad.lower():
                return sehir.sicaklik
        return None

    def tavsiye_ver(self, sicaklik):
        if sicaklik < 0:
            return "Hava soğuk, sıkı giyinin."
        elif 0 <= sicaklik < 15:
            return "Hava serin, mont almayı unutmayın."
        else:
            return "Hava güzel, rahat giyin."

    def listele(self):
        if not self.sehirler:
            print("Henüz hiçbir şehir eklenmedi.")
        else:
            print("\nKayıtlı Şehirler ve Sıcaklıklar:")
            for sehir in self.sehirler:
                print(sehir)


def main():
    hava = HavaDurumu()
    while True:
        print("\n1. Şehir Ekle\n2. Hava Durumu Sorgula\n3. Şehirleri Listele\n4. Çıkış")
        secim = input("Bir seçenek girin: ")
        if secim == "1":
            ad = input("Şehir adı: ")
            try:
                sicaklik = float(input("Sıcaklık (°C): "))
                hava.sehir_ekle(ad, sicaklik)
                print(f"{ad} başarıyla eklendi.")
            except ValueError:
                print("Lütfen geçerli bir sıcaklık değeri girin!")
        elif secim == "2":
            ad = input("Hava durumunu sorgulamak istediğiniz şehir: ")
            sicaklik = hava.sicaklik_sorgula(ad)
            if sicaklik is not None:
                print(f"{ad} için sıcaklık: {sicaklik}°C")
                print(hava.tavsiye_ver(sicaklik))
            else:
                print("Şehir bulunamadı!")
        elif secim == "3":
            hava.listele()
        elif secim == "4":
            print("Uygulamadan çıkılıyor...")
            break
        else:
            print("Geçersiz bir seçim yaptınız, tekrar deneyin.")


if __name__ == "__main__":
    main()